@host=http://localhost:5209
@subscriptionId=163C48FD-CC05-4BA8-BA58-397916D87D05

POST {{host}}/subscriptions/{{subscriptionId}}/gyms
Content-Type: application/json

{
    "Name": "Amiko's gym"
}

###

http://localhost:5051/subscriptions/51b5d6fd-75fe-44d9-a56f-2dcde66fad56/gyms/59bf64b3-fee6-4403-9631-d1a4f57cb032