@host=http://localhost:5209
@userId=912C108C-0F04-4EAA-A43C-536403AEB072
@token=

### Admin
POST {{host}}/users/{{userId}}/profiles/admin
Authorization: Bearer {{token}}

### Trainer
POST {{host}}/users/{{userId}}/profiles/trainer

### Participant
POST {{host}}/users/{{userId}}/profiles/participant