@host=http://localhost:5209
@adminId=5A35959C-F45C-4CA3-AC4A-DD7AB7EE9CBB

POST {{host}}/Subscriptions
Content-Type: application/json

{
    "SubscriptionType": "Starter",
    "AdminId": "{{adminId}}"
}
